name: Upload To Azure
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, build
        run: |
          yarn install
          yarn build --prod
        env:
          CI: true
      - uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: "./dist/felixkhoi"
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_INDEX_DOCUMENT_NAME: "index.html"
          AZURE_ERROR_DOCUMENT_NAME: ""
